apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ml-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: digitalartist221/ml_project-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_BACKEND_URL
        - name: CHOKIDAR_USEPOLLING
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: CHOKIDAR_USEPOLLING
